# mrs 插件配置文件
# 圣遗物属性系统

# 插件基本设置
settings:
  # 是否启用调试模式
  debug: false
  # 是否打印圣遗物效果统计的详细日志（优先于 settings.debug）
  relic.debug_effects: false
  
  # 默认语言
  language: zh_CN

# 圣遗物系统设置
relic:
  # 是否启用圣遗物系统
  enabled: true
  # 是否启用“套装”系统（关闭后将以自定义套装id生成，不校验 sets.yml）
  sets:
    enabled: true
    custom_set_id: custom
    custom_set_name: 自定义圣遗物
  
  # 属性计算方式：additive（加法）或 multiplicative（乘法）
  calculation_mode: additive
  
  # 主词条随等级线性增长（每级=base+level*step）
  mainstat:
    scale: true
    # 当 attribute_pool.yml 未指定 step 时使用该默认值
    step_default: 1.0
  
  # 仓库最大容量（仅YAML存储模式有效）
  warehouse_max_size: 1000
  
  # 存储方式：
  # - YAML: 传统YAML文件存储（向后兼容）
  # - INVENTORY: 独立的圣遗物存储系统（推荐，类似末影箱原理但不占用末影箱）
  storage_mode: INVENTORY
  
  # 独立存储设置
  inventory_storage:
    # 是否自动迁移YAML数据到独立存储
    auto_migrate: true
    # 迁移后是否保留YAML备份
    keep_backup: true
    # 存储文件格式：DAT（二进制，类似Minecraft原生） 或 YAML（文本格式）
    file_format: DAT
  
# 消息配置
messages:
  prefix: "§6[mrs]§r "
  no_permission: "§c你没有权限执行此操作！"
  reload_success: "§a配置重载成功！"

# 集成配置（推荐与 AttributePlus 深度集成）
integration:
  attributeplus:
    enabled: true
    namespace: RelicSystem
    # 使用 AP 原生 API 对接（true）或回退为命令模板（false）
    api_mode: true
    # 百分比缩放：1.0 表示 15 => 15（AP会自动处理为%），0.01 表示 15 => 0.15
    percent_scale: 1.0
    stat_map:
      HP_FLAT: health
      ATK_FLAT: attack
      HP_PCT: health
      ATK_PCT: attack
      DEF_PCT: armor
      CRIT_RATE: crit
      CRIT_DMG: crit_rate
      MOVE_SPEED: moving
      HEAL_BONUS: restore_ratio
      # 元素/万能伤害改为具体战斗属性
      FIRE_CHANCE: fire
      FIRE_DAMAGE: fire_damage
      VAMPIRE_CHANCE: vampire
      VAMPIRE_RATE: vampire_rate
      HIT: hit
      FROZEN_CHANCE: frozen
      FROZEN_INTENSITY: frozen_intensity
      LIGHTNING_CHANCE: lightning
      LIGHTNING_DAMAGE: lightning_damage
      SUNDER_ARMOR: sunder_armor
      SEE_THROUGH: see_through
      BREAK_SHIELD: break_shield
      ARMOR: armor
      DEFENSE: defense
      PVP_DEFENSE: pvp_defense
      PVE_DEFENSE: pve_defense
      CRIT_RESIST: crit_resist
      VAMPIRE_RESIST: vampire_resist
      REFLECTION_CHANCE: reflection
      REFLECTION_RATE: reflection_rate
      DODGE_CHANCE: dodge
      SHIELD_BLOCK_CHANCE: shield_block
      REMOTE_IMMUNE: remote_immune
    # 显式指定作为百分比处理的键（其余使用 _PCT 后缀类型自动识别）
    percentage_keys:
      - crit
      - crit_rate
      - vampire_rate
      - moving
      - restore_ratio
      - fire
      - vampire
      - hit
      - frozen
      - frozen_intensity
      - lightning
      - sunder_armor
      - see_through
      - break_shield
      - armor
      - crit_resist
      - vampire_resist
      - reflection
      - reflection_rate
      - dodge
      - shield_block
      - remote_immune
      - pve_attack
      - pvp_attack
    operation:
      default: add
    command_mode:
      enabled: true
      apply_each:
        - "ap set %player% %namespace%:%key% %value%"
      clear_all:
        - "ap clear %player% %namespace%"

