# GemRelic 插件配置文件
# 圣遗物属性系统

# 插件基本设置
settings:
  # 是否启用调试模式
  debug: false
  
  # 默认语言
  language: zh_CN

# 圣遗物系统设置
relic:
  # 是否启用圣遗物系统
  enabled: true
  
  # 属性计算方式：additive（加法）或 multiplicative（乘法）
  calculation_mode: additive
  
  # 仓库最大容量
  warehouse_max_size: 1000
  
# 消息配置
messages:
  prefix: "§6[GemRelic]§r "
  no_permission: "§c你没有权限执行此操作！"
  reload_success: "§a配置重载成功！"

# 集成配置
integration:
  attributeplus:
    enabled: true
    namespace: GemRelic
    stat_map:
      CRIT_RATE: crit_chance
      CRIT_DMG: crit_damage
      ATK_SPEED: attack_speed
      MOVE_SPEED: move_speed
      LUCK: luck
      KB_RES: knockback_resistance
    operation:
      default: add

