# mrs 插件配置文件
# 圣遗物属性系统

# 插件基本设置
settings:
  # 是否启用调试模式
  debug: true
  # 是否打印圣遗物效果统计的详细日志（优先于 settings.debug）
  relic.debug_effects: false
  
  # 默认语言
  language: zh_CN

# 圣遗物系统设置
relic:
  # 是否启用圣遗物系统
  enabled: true
  # 圣遗物最大等级（防止输入过大数字导致性能问题）
  max_level: 20
  # 是否启用“套装”系统（关闭后将以自定义套装id生成，不校验 sets.yml）
  sets:
    enabled: true
    custom_set_id: custom
    custom_set_name: 自定义圣遗物
  
  # 属性计算方式：additive（加法）或 multiplicative（乘法）
  calculation_mode: additive
  
  # 主词条随等级线性增长（每级=base+level*step）
  mainstat:
    scale: true
    # 当 attribute_pool.yml 未指定 step 时使用该默认值
    step_default: 1.0
  
  # 仓库最大容量（仅YAML存储模式有效）
  warehouse_max_size: 1000
  
  # 存储方式：
  # - YAML: 传统YAML文件存储（向后兼容）
  # - INVENTORY: 独立的圣遗物存储系统（推荐，类似末影箱原理但不占用末影箱）
  storage_mode: INVENTORY
  
  # 独立存储设置
  inventory_storage:
    # 是否自动迁移YAML数据到独立存储
    auto_migrate: true
    # 迁移后是否保留YAML备份
    keep_backup: true
    # 存储文件格式：DAT（二进制，类似Minecraft原生） 或 YAML（文本格式）
    file_format: DAT
  
# 消息配置
messages:
  prefix: "§6[mrs]§r "
  no_permission: "§c你没有权限执行此操作！"
  reload_success: "§a配置重载成功！"

# 集成配置（推荐与 AttributePlus 深度集成）
integration:
  attributeplus:
    enabled: true
    namespace: RelicSystem
    # 使用 AP 原生 API 对接（true）或回退为命令模板（false）
    api_mode: true
    # 百分比缩放：1.0 表示 15 => 15，0.01 表示 15 => 0.15
    # 注意：AP的tempPercentage可能期望0-1的小数，而不是0-100的整数
    # 如果属性显示异常，请尝试修改此值（推荐先尝试 0.01）
    percent_scale: 1.0
    
    # 属性名称映射（占位符 -> 中文服务器键）
    # 如果不配置此项，将使用默认映射
    # 默认映射适用于大部分 AttributePlus 配置
    # 仅当你的 AP 配置使用了自定义属性名称时才需要修改
    name_mapping:
      health: "生命力"
      attack: "物理伤害"
      defense: "物理防御"
      pvp_attack: "PVP伤害"
      pve_attack: "PVE伤害"
      pvp_defense: "PVP防御"
      pve_defense: "PVE防御"
      real_attack: "真实伤害"
      crit: "暴击几率"
      crit_rate: "暴伤倍率"
      vampire: "吸血几率"
      vampire_rate: "吸血倍率"
      shoot_speed: "箭矢速度"
      shoot_spread: "箭术精准"
      shoot_through: "箭矢穿透率"
      fire: "燃烧几率"
      fire_damage: "燃烧伤害"
      frozen: "冰冻几率"
      frozen_intensity: "冰冻强度"
      lightning: "雷击几率"
      lightning_damage: "雷击伤害"
      hit: "命中几率"
      sunder_armor: "破甲几率"
      see_through: "护甲穿透"
      break_shield: "破盾几率"
      armor: "护甲值"
      crit_resist: "暴击抵抗"
      vampire_resist: "吸血抵抗"
      reflection: "反弹几率"
      reflection_rate: "反弹倍率"
      dodge: "闪避几率"
      shield_block: "盾牌格挡率"
      remote_immune: "箭伤免疫率"
      moving: "移速加成"
      restore: "生命恢复"
      restore_ratio: "百分比恢复"
    
    stat_map:
      # 基础属性（严格对应 AP）
      HP_FLAT: health
      ATK_FLAT: attack
      DEF_FLAT: defense
      HP_PCT: health
      ATK_PCT: attack
      DEF_PCT: defense
      # 攻击属性
      PVP_ATK: pvp_attack
      PVE_ATK: pve_attack
      REAL_ATK: real_attack
      CRIT_CHANCE: crit
      CRIT_RATE: crit_rate
      VAMPIRE_CHANCE: vampire
      VAMPIRE_RATE: vampire_rate
      FIRE_CHANCE: fire
      FIRE_DAMAGE: fire_damage
      HIT: hit
      FROZEN_CHANCE: frozen
      FROZEN_INTENSITY: frozen_intensity
      LIGHTNING_CHANCE: lightning
      LIGHTNING_DAMAGE: lightning_damage
      SUNDER_ARMOR: sunder_armor
      SEE_THROUGH: see_through
      BREAK_SHIELD: break_shield
      # 防御属性
      PVP_DEF: pvp_defense
      PVE_DEF: pve_defense
      ARMOR: armor
      CRIT_RESIST: crit_resist
      VAMPIRE_RESIST: vampire_resist
      REFLECTION_CHANCE: reflection
      REFLECTION_RATE: reflection_rate
      DODGE_CHANCE: dodge
      SHIELD_BLOCK: shield_block
      REMOTE_IMMUNE: remote_immune
      # 其他属性
      RESTORE: restore
      RESTORE_RATIO: restore_ratio
      MOVE_SPEED: moving
    # 显式指定作为百分比处理的键（其余使用 _PCT 后缀类型自动识别）
    # 注意：以下列表用于补充 _PCT 后缀无法识别的百分比属性
    percentage_keys:
      # 基础百分比属性（与 HP_PCT/ATK_PCT/DEF_PCT 对应）
      # 注意：不要在这里添加 health/attack/defense，因为它们通过 _PCT 后缀已识别
      # 攻击类百分比
      - crit
      - crit_rate
      - vampire_rate
      - fire
      - vampire
      - hit
      - frozen
      - frozen_intensity
      - lightning
      - sunder_armor
      - see_through
      - break_shield
      - pve_attack
      - pvp_attack
      # 防御类百分比
      - armor
      - crit_resist
      - vampire_resist
      - reflection
      - reflection_rate
      - dodge
      - shield_block
      - remote_immune
      # 其他类百分比
      - moving
      - restore_ratio
    operation:
      default: add
    command_mode:
      enabled: true
      apply_each:
        - "ap set %player% %namespace%:%key% %value%"
      clear_all:
        - "ap clear %player% %namespace%"

